### ISSUE TITLE
Bug in future<void>

### ISSUE THREAD

**Issue by jamboree** [ned14/boost.monad#1]
This self-contained example failed to compile (MSVC14)

```c++
#include <boost/monad/future.hpp>

int main()
{
    boost::monad::lightweight_futures::future<void> f;
    f.get();
    return 0;
}
```

If you change `void` to `int`, it compiles w/o problem. Is `future<void>` not supported?

**Comment by ned14** [comment]
Confirmed. Looks like I broke it last night and the test suite was not testing that exact code (it is now). I'm working on a fix. Thanks for the report.

**Comment by ned14** [comment]
Actually it's a typo and has been there for some weeks. Fixed over here, I'll push it when I get off the train. Thanks for the report.
